name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Alexei-Ionov
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      # Commit and Push the Snake Animation to the repository
      - name: Commit and Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update GitHub contribution grid snake animation"
          git push https://${{ secrets.GH_PAT }}@github.com/Alexei-Ionov/Alexei-Ionov.git main
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
